---
- name: Add or update user and set password
  action: user name={{ username }} password={{ password }} shell=/bin/bash generate_ssh_key=yes ssh_key_bits=4096

- name: Change user directory permissions to 750
  file: path=/home/{{ username }} state=directory mode=750

- name: Add or udpate authorized key
  action: authorized_key user={{ username }} key="{{ lookup('file', id_rsa_path) }}"
  when: id_rsa_path is defined

- name: Add user to sudoers
  action: lineinfile dest=/etc/sudoers regexp="{{ username }} ALL" line="{{ username }} ALL=(ALL) ALL" state=present  
  when: sudoers == 'y' 

- name: Remove user to sudoers
  action: lineinfile dest=/etc/sudoers regexp="{{ username }} ALL" line="{{ username }} ALL=(ALL) ALL" state=absent
  when: sudoers == 'n' 

- name: Add user to docker group 
  action: group name=docker state=present
  when: docker_group == 'y'

- name: Add user to docker group 
  action: user name={{ username }} append=yes groups=docker 
