---
- name: Create swap space
  command: dd if=/dev/zero of=/extraswap bs=1M count={{ swap_size }}
  when: ansible_swaptotal_mb < 1

- name: Make swap
  command: mkswap /extraswap
  when: ansible_swaptotal_mb < 1

- name: Add to fstab
  action: lineinfile dest=/etc/fstab regexp="extraswap" line="/extraswap none swap sw 0 0" state=present

- name: Turn swap on
  command: swapon -a

- name: Set swapiness
  shell: echo 10 | sudo tee /proc/sys/vm/swappiness

- name: improve caching 
  command: sysctl vm.vfs_cache_pressure=50

- name: improve swappiness caching
  command: sysctl vm.swappiness=10

- name: improve caching permanently
  action: lineinfile dest=/etc/sysctl.conf regexp="vfs_cache_pressure" line="vm.vfs_cache_pressure = 50" state=present

- name: improve swappiness caching permanently
  action: lineinfile dest=/etc/sysctl.conf regexp="vm.swappiness" line="vm.swappiness=10" state=present

